### ISSUE TITLE
Hackerpack item component.

### ISSUE THREAD

**Issue by Earlo** [hackjunction/hackplatform#130]
There is no component for hackerpack item, there should be one.

**Comment by khenriksson** [comment]
This is fixed in branch [hackerpack-component](https://github.com/hackjunction/hackplatform/tree/hackerpack-component), but I'd appreciate if you could take a look and see that all the changes are okey for now. It's still using the same kind of design etc as the old one, and the reads the json file in the index, but at least there's a component. 

Also fixed a spelling mistake on the first page.

Feedback appreciated.
