### ISSUE TITLE
Allow user to delete all data associated with them.

### ISSUE THREAD

**Issue by Earlo** [hackjunction/hackplatform#31]
GDPR compliance with less work for the administrative team.

**Comment by lappalj4** [comment]
So, to make this happen we should create a new tab under the /account page, i.e. "Privacy". Under that tab there will be various privacy-related settings, one of which is this "Forget me" functionality.

**Required features (frontend):** 
- A big red dangerous-looking button to initiate the forgetting of oneself
- Some sort of double-verification, e.g. a popup which asks the user to write "Yes, I'm sure" or something similar.
- Once the deletion is done, log the user out. After this the user will no longer be able to log in on that account. 

**What should happen (backend):**

In general we don't want to delete any of the data, as to not mess with any potential relations in the database, we just want to anonymise it entirely.

1) Anonymise the user's UserProfile object -> Remove all other fields except for `userId`, set `firstName`, `lastName` and `email` to some filler values like "Anonymous Owl owl@anonymous.com"

2) Anonymise all of the user's registration objects. We need to be careful here because some of these details we need to keep for legal reasons. For each registration object: 

Leave as is: 
- event
- user (it's a relation to the anonymised user object)
- status
- assignedTo
- rating
- ratedBy
- travelGrant
- travelGrantStatus
- travelGrantDetails (contains PI but we need to keep this for legal reasons)
- travelGrantComment
- travelGrantAmount

Anonymise:
- tags (set this to empty array)
- answers (set this to only contain filler values for firstName, lastName & email)

3) Use the Auth0 management API to block the user from signing in. We could just as well delete the user, but I'm not entirely sure of the consequences if they decide to create a new user with the same e.g. Google account - does Auth0 give them the same userId? In that case they would be able to log in to their anonymised user account which we don't want to happen. I think we are better off just blocking them from signing in.

https://community.auth0.com/t/block-user-via-api-call/12970

**Comment by lappalj4** [comment]
Oh by the way, has there been any progress on this?

**Comment by lappalj4** [comment]
If not, I can take a look at this
