### ISSUE TITLE
Introduce i18n internationalisation to the platform

### ISSUE THREAD

**Issue by biharygergo** [hackjunction/hackplatform#41]
The platform should allow additional languages to be used apart from English. This would require that all strings in the app right now be extracted to an i18n library, where in the future translators or community contributors could translate them to their own language. 

There are multiple elegant ways to solve this, but this is a critical issue for use in other countries, where English may not be preferred. Let's discuss this sometime!

**Comment by lappalj4** [comment]
I like the idea, however it'll be quite a complex task to do properly. This is because a lot of the content on the platform is user-generated, and to do i18n properly all of that would need to be translateable to however many languages one wants to support. For the moment we can for sure replace hardcoded strings with i18n constants, which would be a good start, but won't do much for truly making the platform multilingual. 

Or would the idea be to support only a single language per deployment?

**Comment by lappalj4** [comment]
I would prefer jumping on this once the platform is truly stable feature-wise, since doing this will introduce an additional layer of complexity in the app and reduce our flexibility in easily being able to introduce new features and make changes to existing ones.

**Comment by Earlo** [comment]
It's a good nice to have feature, especially for more local JunctionX events where people mostly use their local language. But not really priority right now.

In Junction main event, and other multinational hackathons we want the entries to be in English, since it makes the process of judging easier.

**Comment by Earlo** [comment]
#109 Closes this : )

Thanks @khenriksson
